### ISSUE TITLE
IndexError: string index out of range

### ISSUE THREAD

**Issue by Kwame261** [bolianchen/pytorch_depth_from_videos_in_the_wild#20]
Hello I tried  training  on some data from kitti.

I first run  the generate on a sample and   then the train.py.

This is the error I get.

IndexError: string index out of range

Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main_worker(0, world_size, method, gpus, dist_backend, unknown_args1)
  File "train.py", line 25, in main_worker
    trainer = method_zoo[method][1](opts)
  File "/home/kwameampofo/pytorch_depth_from_videos_in_the_wild/trainers/wild_trainer.py", line 29, in __init__
    super(WildTrainer, self).__init__(options)
  File "/home/kwameampofo/pytorch_depth_from_videos_in_the_wild/trainers/base_trainer.py", line 34, in __init__
    self._preliminary_setups()
  File "/home/kwameampofo/pytorch_depth_from_videos_in_the_wild/trainers/base_trainer.py", line 99, in _preliminary_setups
    if inp.lower()[0] == "y":
IndexError: string index out of range

Can you please help me debug what is causing this?

**Comment by bolianchen** [comment]
Hello, @Kwame261 

Sorry for my late response, have you resolved this issue.  If not, please share the arguments you used. Thanks.

**Comment by Kwame261** [comment]
Hello, Thank you for your response. I have resolved this issue
