### ISSUE TITLE
question on gen_data.py

### ISSUE THREAD

**Issue by bcextreme** [bolianchen/pytorch_depth_from_videos_in_the_wild#24]
Hi @bolianchen ,
I want to use gen_data.py to pretrained by using the KITTI dataset, but there's always a NameError:

`multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "E:\Anaconda\envs\dp\lib\multiprocessing\pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "E:\Anaconda\envs\dp\lib\multiprocessing\pool.py", line 48, in mapstar
    return list(map(*args))
  File "E:\PycharmProj\pytorch_depth_estimation\gen_data.py", line 197, in _gen_example_star
    return _gen_example(*params)
  File "E:\PycharmProj\pytorch_depth_estimation\gen_data.py", line 169, in _gen_example
    add_to_file, example = dataloader.get_example_with_index(i)
NameError: name 'dataloader' is not defined
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "E:\PycharmProj\pytorch_depth_estimation\gen_data.py", line 227, in <module>
    _generate_data()
  File "E:\PycharmProj\pytorch_depth_estimation\gen_data.py", line 122, in _generate_data
    pool.map(
  File "E:\Anaconda\envs\dp\lib\multiprocessing\pool.py", line 364, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "E:\Anaconda\envs\dp\lib\multiprocessing\pool.py", line 771, in get
    raise self._value
NameError: name 'dataloader' is not defined`

I think maybe the gloabal variable ' dataloader' can't be found in the multiprocessing pool? I'm a rookie of python and CV, can you please tell me how to solve this problem..

Thanks.

**Comment by Ljiaooo** [comment]
It seems to be a multiprocess error which is caused by the Windows system, you can try to set --single_process (slow processing speed), or run the code on Linux.

**Comment by bcextreme** [comment]
@Ljiaooo 
Thanks for your answer, it seems like the global variable isn't being passed into the multiprocessing pool correctly on Windows system, but I've fixed that. I have another question to ask you. From the results I get by depth inference, the estimate_depth() function gives us the depth matrix, which contains the relative depth. But what if I want to get the absolute depth, the true distance from the camera to a certain pixel in the image, how can I get that?

**Comment by bolianchen** [comment]
Hello @bcextreme 
One method we tried is to get the linear factor(C) between the output depth and true distance via calibration.
true_distance = C * output_depth
We used sparse radar signals in a short clip to calibrate an average linear factor; however, measuring the true distances corresponding to several pixels might be fine, too.

By the way, it would be appreciated if you may share or send a pull request about the fix of the multiprocessing issue for Windows. Thank you.
