### ISSUE TITLE
TypeError: 'tuple' object is not callable

### ISSUE THREAD

**Issue by imneonizer** [bolianchen/pytorch_depth_from_videos_in_the_wild#6]
I am using kitti dataset to train, here are the steps I followed:

1. ###### Download dataset

   ````sh
   bash ./datasets/data_prep/kitti_raw_downloader.sh
   ````

2. process dataset

   ````sh
   python gen_data.py \
       --dataset_name kitti_raw_stereo \
       --dataset_dir ./kitti_raw \
       --save_dir ./processed_dataset \
       --img_height 480 \
       --img_width 640 \
       --mask color
   ````

3. Model training

   ````sh
   python train.py \
       --data_path ./processed_dataset \
       --png \
       --learn_intrinsics \
       --weighted_ssim \
       --boxify \
       --model_name ./weights/
   ````

**Error:**

````shell
Training model named:
   ./weights/
Models and tensorboard events files are saved to:
   /media/nvme/nitin/depth_estimation/pytorch_depth_from_videos_in_the_wild/models
Training is using:
   cuda:0
Downloading: "https://download.pytorch.org/models/resnet18-f37072fd.pth" to /root/.cache/torch/hub/checkpoints/resnet18-f37072fd.pth
100%|██████████████████████████████████████| 44.7M/44.7M [00:03<00:00, 12.0MB/s]
/opt/conda/lib/python3.8/site-packages/torchvision/transforms/transforms.py:321: UserWarning: Argument interpolation should be of type InterpolationMode instead of int. Please, use InterpolationMode enum.
  warnings.warn(
There are 1473 training items and 171 validation items

>> Epoch: 1
Training
  0%|                                                   | 0/122 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "train.py", line 61, in <module>
    main_worker(0, world_size, method, gpus, dist_backend, unknown_args1)
  File "train.py", line 26, in main_worker
    trainer.train()
  File "/media/nvme/nitin/depth_estimation/pytorch_depth_from_videos_in_the_wild/trainers/base_trainer.py", line 429, in train
    curr_train_loss, curr_val_loss = self.run_epoch()
  File "/media/nvme/nitin/depth_estimation/pytorch_depth_from_videos_in_the_wild/trainers/base_trainer.py", line 529, in run_epoch
    for batch_idx, inputs in enumerate(trange):
  File "/opt/conda/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1203, in _next_data
    return self._process_data(data)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1229, in _process_data
    data.reraise()
  File "/opt/conda/lib/python3.8/site-packages/torch/_utils.py", line 438, in reraise
    raise exception
TypeError: Caught TypeError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/opt/conda/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/media/nvme/nitin/depth_estimation/pytorch_depth_from_videos_in_the_wild/datasets/custom_mono_dataset.py", line 224, in __getitem__
    self.preprocess(inputs, color_aug)
  File "/media/nvme/nitin/depth_estimation/pytorch_depth_from_videos_in_the_wild/datasets/mono_dataset.py", line 113, in preprocess
    inputs[(n + "_aug", im, i)] = self.to_tensor(color_aug(f))
TypeError: 'tuple' object is not callable
````

**Comment by bolianchen** [comment]
@imneonizer 
Thanks for reporting the issue.  
Would you please print the first 10 lines of ./processed_dataset/train_files.txt?
I suspect the exception was caused by spaces used in the names of some of the raw video files.

**Comment by imneonizer** [comment]
Here it is:
````
2011_09_26_drive_0035_sync_02/ 0000000007
2011_09_26_drive_0035_sync_02/ 0000000008
2011_09_26_drive_0035_sync_02/ 0000000005
2011_09_26_drive_0035_sync_02/ 0000000009
2011_09_26_drive_0035_sync_02/ 0000000004
2011_09_26_drive_0035_sync_02/ 0000000002
2011_09_26_drive_0035_sync_02/ 0000000012
2011_09_26_drive_0035_sync_02/ 0000000001
2011_09_26_drive_0035_sync_02/ 0000000003
2011_09_26_drive_0035_sync_02/ 0000000011
````

I see spaces before the file name, should I remove them manually?

**Comment by bolianchen** [comment]
No need for now, I didn't notice you are using KITTI data, please give me some time to recheck the issue.

**Comment by bolianchen** [comment]
@imneonizer 
I guess you may be using an incompatible Pytorch version. I faced this issue when I tried Pytorch 1.8. Please try either of the verified versions below:
- Pytoch 1.5 or Pytoch 1.7.1

By the way, the original resolution of KITTI data is 1224x370, so converting them with 640x480 resolution would distort the images.

**Comment by imneonizer** [comment]
Thanks, PyTorch version `1.7.1` worked.
````
pip install torch==1.7.1+cu110 torchvision==0.8.2+cu110 torchaudio==0.7.2 -f https://download.pytorch.org/whl/torch_stable.html
````

My goal was to test the training script execution so `640x480` is fine for now.

**Comment by bolianchen** [comment]
Added an explicit instruction command to install PyTorch of the tested version.
