### ISSUE TITLE
Couldn't find any class folder

### ISSUE THREAD

**Issue by 777-en** [bolianchen/pytorch_depth_from_videos_in_the_wild#7]
Hi, thank you for your nice project. I tried to generate dataset based on my own videos but some problems occurred. My videos are in `data/video` and I want to save the processed dataset in `data/processed`. So I run the following command:
```
python gen_data.py \
    --dataset_name video \
    --dataset_dir data/video/ \
    --save_dir data/processed \
    --img_height 480 \
    --img_width 640 \
    --mask color
```

But I got the error as follows:
```
Traceback (most recent call last):
  File "gen_data.py", line 217, in <module>
    _generate_data()
  File "gen_data.py", line 145, in _generate_data
    FLAGS.save_img_ext)
  File "/data/student/zhanzhang/pytorch_depth_from_videos_in_the_wild/datasets/auxiliary_datasets.py", line 20, in __init__
    is_valid_file=make_image_checker(img_ext)
  File "/home/student/.conda/envs/zz/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 313, in __init__
    is_valid_file=is_valid_file)
  File "/home/student/.conda/envs/zz/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 145, in __init__
    classes, class_to_idx = self.find_classes(self.root)
  File "/home/student/.conda/envs/zz/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 221, in find_classes
    return find_classes(directory)
  File "/home/student/.conda/envs/zz/lib/python3.6/site-packages/torchvision/datasets/folder.py", line 42, in find_classes
    raise FileNotFoundError(f"Couldn't find any class folder in {directory}.")
FileNotFoundError: Couldn't find any class folder in data/processed.
```

I am confused, could you help me?

**Comment by 777-en** [comment]
OH I think I figured it out. It turned out that my video is with extension `.mpg`, but `.mp4` is required.

**Comment by bolianchen** [comment]
Hi Quentin

It seems no images are retrieved from the videos supposed to be in data/video/.
Would you please list the files in data/video?
By the way, if it is ok for you, please post this issue to the issues
board. Someone else might be faced with the same issue.
Thanks a lot.

Best,
Bolian

**Comment by 777-en** [comment]
Thank you for your reply. At first the videos in `data/video` are like this:
```
1.mpg
2.mpg
3.mpg
...
```

As I run the command mentioned above, it raised the error `FileNotFoundError: Couldn't find any class folder in data/processed.' 
Then I changed the format of the videos in `data/video` to this:
```
1.mp4
2.mp4
3.mp4
...
```
The problem turned to be fixed.

**Comment by bolianchen** [comment]
@777-en 

Thank you very much for your sharing. I will revise README to let others know clearly gen_data.py does not work for mpg for now.

Best,
Bolian

**Comment by bolianchen** [comment]
Updated README to emphasize videos should be in mp4 format.
